apiVersion: apps/v1
kind: Deployment
metadata:
  name: connection
  labels:
    app: connection
    service: connection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connection
      service: connection
  template:
    metadata:
      labels:
        app: connection
        service: connection
    spec:
      containers:
      - name: connection-container
        image: hhana982/connection:1.<version>
        ports:
        - containerPort: 5000

