apiVersion: v1
kind: Service
metadata:
  name: connection
  labels:
    service: connection
spec:
  selector:
    app: connection
    service: connection
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP