apiVersion: apps/v1
kind: Deployment
metadata:
  name: connection-mysql-deployment
  labels:
    app: mysql
    service: connection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      service: connection
  template:
    metadata:
      labels:
        app: mysql
        service: connection
    spec:
      containers:
      - name: connection-mysql
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'rootpassword'
