apiVersion: v1
kind: Service
metadata:
  name: connection-mysql
  labels:
    app: mysql
    service: connection
spec:
  selector:
    app: mysql
    service: connection
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP